### ISSUE TITLE
Request to add repository and license fields to package.json

### ISSUE THREAD

**Issue by poibr01** [dlumbrer/kbn_network#12]
While not earth shattering by any means, newer versions of node throw WARN's up for git repo and licensing info missing in the package.json file.  Would like to have the following added to the package.json to avoid these two messages during the npm install.

```npm WARN network_vis@5.0.0-rc1 No repository field.```
```npm WARN network_vis@5.0.0-rc1 No license field.```

**Comment by dlumbrer** [comment]
Thats rigth!, I'm going to add it :+1:
