### ISSUE TITLE
Error when trying to install release 

### ISSUE THREAD

**Issue by AmrinderRai** [dlumbrer/kbn_network#15]
Hi, 

I am having issues installing release 4.x for my Kibana 4.6.4 

I am getting the following modules are not found:

- 'vis' ,
- 'randomcolor',
- 'css-element-queries/src/ElementQueries',
- 'css-element-queries-src/src/ResizeSensor'

in kibana/installedPlugins/kbn_network/public.

**Comment by dlumbrer** [comment]
Hi, follow these steps:

Try to change the name of the folder "kbn_network" to "network_vis"

After go to "installedPlugins/network_vis" and do "npm install"


Now it should work

**Comment by AmrinderRai** [comment]
Hi, thanks for the response. 

I am still having the same issue. I'm not able to use NPM on the system I'm working on, but having been using the following linux command (as in elastic docs):
`sudo bin/kibana plugin --install network_vis --url file:///network_vis.tar.gz`

Much appreciate any responses. Thanks

**Comment by dlumbrer** [comment]
To build a zip with the release, you need to use npm to install the dependencies:

First go to 

```
mkdir kibana
cd kibana
git clone -b 4.x https://github.com/dlumbrer/kbn_network.git network_vis
cd network_vis
npm install
cd ../..
zip -r network_vis-<version>.zip kibana --exclude kibana/network_vis/.git\*
```

Now you have on "kibana/" a zip with the plugin and all the dependencies. After, decompress the zip on your "$KIBANA_HOME/installedPlugins/"

**Comment by AmrinderRai** [comment]
That helped. Thank you so much!
