### ISSUE TITLE
Better performance

### ISSUE THREAD

**Issue by TheReal1604** [dlumbrer/kbn_network#16]
Hi,

big thanks for this really awesome plugin!

Do you see any chance to speed up the render process with many nodes on the sheet? Like Top 50 Nodes which individually can also have 50 nodes.. This lags heavy in the browser - mostly because its jailed to one cpu core i think.

Maybe you already have some hints or practices to speed things up for big visualisations?

Edit: Some more info regarding to my performance issues. I use Kibana mostly in google chrome and if I render multiple visualizations - one after another (for testing purposes for example) - and switch then to a minimal dashboard with no visualization on it, the cpu load is not decreasing. Only after closing and opening a new tab, the cpu load is normal and the visualizations are fast again. (Sry for the weird description)

**Comment by dlumbrer** [comment]
Hi @TheReal1604,

There are two field to change in the "Options" tab that are very interesting when you want to build huge networks:

- Gravitational constant: Gravity attracts. We like repulsion. So the value is negative. If you want the repulsion to be stronger, decrease the value

- Spring constant: This is how 'sturdy' the springs are. Higher values mean stronger springs.

Try to "play" with this parameters

**Comment by TheReal1604** [comment]
Thanks for your answer, but how effects this settings the rendering performance of the graph? :-)

**Comment by dlumbrer** [comment]
For example: If you decrease the gravitation constant enough for the nodes to be wide apart, the process of rendering the vis.js library is smaller, because it does not have to distribute all the nodes in a small space without being disturbed.

Same thing to change the spring constant.

**Comment by TheReal1604** [comment]
Ah, thanks for the description! I try it.

**Comment by dlumbrer** [comment]
If you have a problem, send me screenshots and I can help you better. :-)
