### ISSUE TITLE
Not working..how do you start?

### ISSUE THREAD

**Issue by DigiAngel** [dlumbrer/kbn_network#17]
I've installed this, but how do I get to it?  Create a new visualization?  Which kind?  I don't see a "Node" anywhere that I've tried.  I restarted Kibana after install, but no success.

**Comment by dlumbrer** [comment]
If you follow the installation steps you must see in the visualizations list the item of this plugin.

Can you send the logs when you install the plugin, the logs when you init Kibana and tell me what version of Kibana are you working?

Also, check on package.json that the "version" tag matches with your Kibana version.

Thanks

**Comment by DigiAngel** [comment]
Ok cool thank you.  I'm on the latest 5.3.0 of Kibana.  I don't see anything in the logs :(

**Comment by dlumbrer** [comment]
Try to change on package.json the "version" tag to "5.3.0"

**Comment by DigiAngel** [comment]
Thanks....unfortunately that maxes the CPU and kibana never fully initializes as I get a page not found.

**Comment by DigiAngel** [comment]
Closing the loop on this...indeed setting version to 5.3.0 fixed this up..thank you.
