### ISSUE TITLE
Kibana 5.4.0 support

### ISSUE THREAD

**Issue by luigiberrettini** [dlumbrer/kbn_network#19]
Hi, I changed the package.json to version 5.4.0 but Kibana freezes on start: after npm install I copied everything to the official Docker container and the run it, but logs say Kibana is not starting.

**Comment by luigiberrettini** [comment]
Same problem with 5.3.2 and 5.3.0 😭

**Comment by dlumbrer** [comment]
I will take a look in the next days, but I'm sure that works in Kibana 5.3.0

Thanks!

**Comment by dlumbrer** [comment]
Hi @luigiberrettini. I had tested the plugin in Kibana 5.4.0 and its works.

![captura de pantalla de 2017-05-17 12-21-57](https://cloud.githubusercontent.com/assets/9249232/26149726/af9a9f7e-3afb-11e7-95a8-b5021ea99c15.png)

Please, change the tag "version" in package.json of the plugin for "5.4.0" for work in Kibana 5.4.0. I think this is the problem.

Reopen the issue if it doesn't work

**Comment by luigiberrettini** [comment]
You are right, it works, but Kibana takes 25 minutes instead of 3 to get up and running

**Comment by dlumbrer** [comment]
This is why you are adding new code into Kibana, Kibana need this time to check everithing is OK and the plugin is completly compatible.
