### ISSUE TITLE
Underlying document schema

### ISSUE THREAD

**Issue by keeyonghan** [dlumbrer/kbn_network#21]
I couldn't understand the underlying document schema for both node-node and node-relation. Are there any examples for these?

**Comment by dlumbrer** [comment]
Do yo see the User guide?

https://github.com/dlumbrer/kbn_network/blob/master/USER_GUIDE.md

I hope that it can help you

**Comment by keeyonghan** [comment]
@dlumbrer I think node-to-node was easier to understand but not so sure the other (node-to-relation). My current document schema is like this (source and target are the same type of nodes):

 - source node 
 - target node
 - strength

In this case, node-to-node is the way to go? If not or if want to go for node-to-relation, how should I change the document schema? Thanks for your great work BTW!

**Comment by dlumbrer** [comment]
Node-Relation will show a network with __only one type of nodes__ (instead Node-Node that show 2 types of nodes):
1. Select Node to select the field that will be show in the nodes
2. Select Relation to select the field that build the relationship between nodes.

P.e: You can build nodes that are "People" and build de relation if they work in the same company
