### ISSUE TITLE
Kibana not loading plugin

### ISSUE THREAD

**Issue by johnpickett** [dlumbrer/kbn_network#23]
Running Kibana 5.4.2, followed install instructions:

cd KIBANA_HOME/plugins
git clone https://github.com/dlumbrer/kbn_network.git network_vis
cd network_vis
npm install

When restarting Kibana:

{"type":"log","@timestamp":"2017-06-22T00:12:15Z","tags":["warning"],"pid":9191,"message":"Plugin \"network_vis\" was disabled because it expected Kibana version \"5.4.0\", and found \"5.4.2\"."}

So I changed the version number as documented in the install notes and restart Kibana again. This time there is no error, but it also never generates a log message about initializing the network_vis plugin like it does all the others. I tried another 'npm install' in the network_vis directory (unfamiliar with npm) as a blind attempt and restarted kibana again. Here's the log:

{"type":"log","@timestamp":"2017-06-22T00:26:03Z","tags":["info","optimize"],"pid":10100,"message":"Optimizing and caching bundles for logtrail, kibana, timelion and status_page. This may take a few minutes"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["info","optimize"],"pid":10100,"message":"Optimization of bundles for logtrail, kibana, timelion and status_page complete in 93.44 seconds"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","plugin:kibana@5.4.2","info"],"pid":10100,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","plugin:elasticsearch@5.4.2","info"],"pid":10100,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","plugin:logtrail@0.1.15","info"],"pid":10100,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","plugin:console@5.4.2","info"],"pid":10100,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","plugin:elasticsearch@5.4.2","info"],"pid":10100,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","plugin:metrics@5.4.2","info"],"pid":10100,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","plugin:timelion@5.4.2","info"],"pid":10100,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["listening","info"],"pid":10100,"message":"Server running at http://127.0.0.1:5601"}
{"type":"log","@timestamp":"2017-06-22T00:27:37Z","tags":["status","ui settings","info"],"pid":10100,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}

I'd expect to see something for network_vis in there somewhere.

root@host:/usr/share/kibana/plugins# ls -la network_vis/
total 56
drwxr-xr-x  6 root   root    4096 Jun 21 18:25 .
drwxrwxr-x  4 kibana kibana  4096 Jun 21 17:46 ..
drwxr-xr-x  8 root   root    4096 Jun 21 17:40 .git
-rw-r--r--  1 root   root      28 Jun 21 17:40 .gitignore
drwxr-xr-x  2 root   root    4096 Jun 21 17:40 images
-rw-r--r--  1 root   root     168 Jun 21 18:00 index.js
-rw-r--r--  1 root   root   11357 Jun 21 17:40 LICENSE
drwxr-xr-x 10 root   root    4096 Jun 21 18:25 node_modules
-rw-r--r--  1 root   root     353 Jun 21 18:25 package.json
drwxr-xr-x  2 root   root    4096 Jun 21 17:40 public
-rw-r--r--  1 root   root    2757 Jun 21 17:40 README.md
-rw-r--r--  1 root   root    3774 Jun 21 17:40 USER_GUIDE.md

root@host:/usr/share/kibana/bin# ./kibana-plugin list
logtrail@0.1.15
network_vis@5.4.2

**Comment by dlumbrer** [comment]
Change the version tag of network_vis/package.json to "5.4.2" and it will work

**Comment by dlumbrer** [comment]
Hi @johnpickett 

Do you see the network_vis in Visualize tab?
