### ISSUE TITLE
Plugin is not compliant with kibana 5.5

### ISSUE THREAD

**Issue by tatdatpham** [dlumbrer/kbn_network#28]
I installed ur plugin in kibana 5.5 and kibana doesn't working. I found some update for custome plugin in here
[https://github.com/elastic/kibana/issues/12707#issuecomment-314216338](https://github.com/elastic/kibana/issues/12707#issuecomment-314216338)

**Comment by dlumbrer** [comment]
I will take a look and solve this problem, thanks!

**Comment by dlumbrer** [comment]
@tatdatpham 

The plugin is now compatible with Kibana 5.5.0, you have it in the "5.5.x" branch

**Comment by tatdatpham** [comment]
Thanks for your update. It's worked !
