### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by fr0gs** [dlumbrer/kbn_network#30]
Hello,

Have you tried to install this plugin in a Docker environment? I have tried several ways but I cannot seem to make it work.

```
FROM kibana:5.5
MAINTAINER esteban.sastre <esteban.sastre@tenforce.com>

ENV KIBANA_PLUGINS /usr/share/kibana/plugins
RUN apt-get update && apt-get install -y git npm

WORKDIR $KIBANA_PLUGINS
RUN git clone https://github.com/dlumbrer/kbn_network.git network_vis && cd network_vis && rm -rf images/ && sed -i "s/5\..\.0/5\.5\.0/g" package.json && npm install
```

Last line just changes the package.json form **5.4.0** to **5.5.0** as you advised, but I cannot seem to find the plugin in visualizations anywhere. I have tried with other plugins and they seem to be properly installed. 
Is is possible that you provide a way like: `kibana-plugin install <url>`?

When it comes to build docker images with plugins it is much easier.

**Comment by dlumbrer** [comment]
If you are using Kibana 5.5.0 you need to install my plugin from this release:

https://github.com/dlumbrer/kbn_network/releases/tag/5.5.X
