### ISSUE TITLE
kibana5.5.0 install plugin failed.

### ISSUE THREAD

**Issue by chenyg0911** [dlumbrer/kbn_network#34]
Download zip file for 5.5.X.
but installation failed.
below is error message
bin/kibana-plugin install file:///esdemo-media/kibana-5.5.0-linux-x86_64/network_vis.zip
Attempting to transfer from file:///esdemo-media/kibana-5.5.0-linux-x86_64/network_vis.zip
Transferring 6607531 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

Also try to use git clone, but kibana start failed.

**Comment by dlumbrer** [comment]
Can you download directly from the branch 5.5.x and try again?

The ZIP of releases has an error, i will delete it.

Thx

**Comment by chenyg0911** [comment]
Did u mean git clone the 5.5.x branch? I will try it. Thanks!

2017-08-23 18:10 GMT+08:00 David Moreno Lumbreras <notifications@github.com>
:

**Comment by chenyg0911** [comment]
git clone the 5.5.x branch. It worked.Great！

2017-08-24 10:35 GMT+08:00 YongGuang Chen <yongguang.chen@gmail.com>:
