### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by rcsmota** [dlumbrer/kbn_network#36]
This should be a stupid question, but after installation how can i make a new visualization graph? 
It's supposed show a new visualization type on visualizer tab, add new visualizer?

![image](https://user-images.githubusercontent.com/31240306/30506509-62467846-9a74-11e7-9c48-4778817acfb7.png)

I follow all steps and the installation looks fine to me.

![image](https://user-images.githubusercontent.com/31240306/30506515-78b17770-9a74-11e7-8fdb-a8458a96111d.png)

Sorry but it's my first Kibana plugin. Now I only use ElastiFlow by Rob Cowart
Thanks

**Comment by robcowart** [comment]
I have written an article on Linkedin that explains how to use kbn_network with data from ElastiFlow. Hopefully this will help.

https://www.linkedin.com/pulse/visualize-network-traffic-connections-elastiflow-kbn-robert-cowart/

**Comment by dlumbrer** [comment]
Wow @robcowart! An excellent article!! 👍 

@rcsmota , are you checked that the version of package.json of the plugin is the same that your kibana?

Thanks!!

**Comment by rcsmota** [comment]
@robcowart  this work perfectly, you did a really nice work in your article. Thanks to you I have kbn_network plugin up an running. Thanks.

@dlumbrer I did miss three steps on last installation explained from rob coward,git checkout 5.5.x, change version of package.json and run kibana at the end.
I know it can be a "natural" process but to me (a newbie) it was crucial. 

Thanks for both, time to learn more about this amazing plugin.
