### ISSUE TITLE
Loading message does not go away

### ISSUE THREAD

**Issue by bluefangs** [dlumbrer/kbn_network#37]
Hi @dlumbrer / @robcowart

I was checkin out the tutorial by Rob from [here](https://www.linkedin.com/pulse/visualize-network-traffic-connections-elastiflow-kbn-robert-cowart?trk=mp-reader-card). I got everything working as portrayed in the tutorial, however, I noticed that there is a message that says "loading network..." in the top right of the canvas that doesn't seem to go away. 

I noticed that it's being generated from [this file](https://github.com/dlumbrer/kbn_network/blob/master/public/network_vis.html). I'm not sure why it stays that way or when it should ideally go away. 

Can you please throw some light as to why it's there and what it's trying to do? Is it actually constantly trying to load something?

Thanks.

**Comment by dlumbrer** [comment]
hi @bluefangs,

there was a bug that I solved just now.

Sorry!
