### ISSUE TITLE
Why not Graph from X-pack

### ISSUE THREAD

**Issue by ErikvdVen** [dlumbrer/kbn_network#38]
Hello dlumbrer, 

Can you tell me a bit more about what made you decide to write your own plugin, instead of using Graph from X-pack, which has almost the same features I suppose? And I mean, reasons besides the fact X-pack is a paid plugin of course ;)

**Comment by dlumbrer** [comment]
Hi @ErikvdVen ,

The question is "Why not?". This plugin was my degree thesis, I think that Open Source is very important in this kind of apps (Kibana). I know that exists X-pack, but for me, is more important the philosophy of Open Source.

When I started developing this plugin, there only exists Kibana 4 and I didn't know anything about Graph (from X-Pack), I've never thought that this plugin could reach so many downloads, and I am really grateful and proud.

Thanks!

**Comment by robcowart** [comment]
@ErikvdVen I would add that...
1. X-Pack Graph is a tool to discover and explore indirect relationships between entities in a dataset. kbn_network displays explicit relationships.
2. X-Pack Graph cannot be added to a dashboard, but kbn_network can.
3. kbn_network is limited to two node types in a single graph. X-Pack graphs allows many more (not sure if there is a hard limit)

In my opinion both provide value that the other can't. I am happy to have both available and use both depending on the problem I am trying to solve.
