### ISSUE TITLE
Loading message always is diplayed on 5.6.1

### ISSUE THREAD

**Issue by TRISAF** [dlumbrer/kbn_network#39]
HI @dlumbrer ,
the plugin works fine in 5.6.1 kibana version, except for the up-right message that says:
Loading network ...
This message is diplayed also after the network was loaded.
Abny idea to fix it?
Many thanks 
Filippo
![immagine](https://user-images.githubusercontent.com/22656565/30922822-8d18df48-a3aa-11e7-847c-cbe3af613b70.png)

**Comment by robcowart** [comment]
Make sure you are using the 5.5.x branch. You will need to edit package.json, changing the kibana version to 5.6.1. The issue you are seeing was fixed about a week ago on the 5.5.x branch.

**Comment by dlumbrer** [comment]
as @robcowart said :+1: , I fixed this error in the latest version.

Please, download the latest version (clone directly from 5.5.x) @TRISAF

**Comment by TRISAF** [comment]
Hi @dlumbrer ,
i follow your suggestion, but the loading banner still remain.
![immagine](https://user-images.githubusercontent.com/22656565/30956663-4e5d5e8a-a438-11e7-9e1e-1fa26c879b1c.png)

Any deeper suggestion for debugging this anomaly?

Many thanks

Filippo

**Comment by dlumbrer** [comment]
It seems that is loading the older version that you had installed before.

I suggest you to delete content the folder KIBANA_HOME/optimize/bundles and launch kibana again.

Thx

**Comment by TRISAF** [comment]
I have deleted the optimize for sure.
I feel i've done everthing correctly, but...
Can you send me a link to be sure that i install the version you suggest?

**Comment by robcowart** [comment]
@TRISAF try the instructions here... https://www.linkedin.com/pulse/visualize-network-traffic-connections-elastiflow-kbn-robert-cowart

Delete KIBANA_HOME/optimize/bundles first.

Edit package.json for version 5.6.1 (which you are using) instead of version 5.5.2 which is described in the instuctions.

This worked fine for me.
