### ISSUE TITLE
warning] Plugin "network_vis" was disabled because it expected Kibana version "1.0.0", and found "5.0.0-beta1

### ISSUE THREAD

**Issue by juerkan** [dlumbrer/kbn_network#4]
Hi 
We want to install your great plugin   “network_vis” (Ubuntu box with kibana 5.0beta1)
 
We go strait with your install instruction:
cd KIBANA_HOME/installedPlugins
git clone https://github.com/dlumbrer/kbn_network.git network_vis
cd network_vis
npm install
 
 
The following warning comes up when we start kibana:
 
log   [11:20:24.229] [warning] Plugin "network_vis" was disabled because it expected Kibana version "1.0.0", and found "5.0.0-beta1".
  log   [11:20:24.636] [info][status][plugin:kibana@5.0.0-beta1] Status changed from uninitialized to green - Ready
  log   [11:20:24.671] [info][status][plugin:elasticsearch@5.0.0-beta1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [11:20:24.679] [info][status][plugin:xpack_main@5.0.0-beta1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [11:20:24.733] [info][status][plugin:graph@5.0.0-beta1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [11:20:24.738] [info][status][plugin:elasticsearch@5.0.0-beta1] Status changed from yellow to green - Kibana index ready
  log   [11:20:24.747] [info][license][xpack] Imported license information from Elasticsearch: mode: trial | status: active | expiry date: 2016-10-25T16:49:01+02:00
  log   [11:20:24.751] [info][status][plugin:xpack_main@5.0.0-beta1] Status changed from yellow to green - Ready
  log   [11:20:24.752] [info][status][plugin:graph@5.0.0-beta1] Status changed from yellow to green - Ready
  log   [11:20:24.781] [info][status][plugin:monitoring@5.0.0-beta1] Status changed from uninitialized to yellow - Waiting for Monitoring Health Check
  log   [11:20:24.920] [warning][reporting] Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml
  log   [11:20:24.925] [info][status][plugin:reporting@5.0.0-beta1] Status changed from uninitialized to green - Ready
  log   [11:20:24.952] [info][status][plugin:monitoring@5.0.0-beta1] Status changed from yellow to green - Ready
  log   [11:20:24.957] [info][status][plugin:security@5.0.0-beta1] Status changed from uninitialized to green - Ready
  log   [11:20:24.959] [warning][security] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml
  log   [11:20:24.965] [warning][security] Session cookies will be transmitted over insecure connections. This is not recommended.
  log   [11:20:25.004] [info][status][plugin:console@5.0.0-beta1] Status changed from uninitialized to green - Ready
  log   [11:20:25.208] [info][status][plugin:timelion@5.0.0-beta1] Status changed from uninitialized to green - Ready
  log   [11:20:25.214] [info][listening] Server running at http://10.229.62.29:5601
  log   [11:20:25.216] [info][status][ui settings] Status changed from uninitialized to green – Ready
 
The Plugin is not visible in kibana 
Please help us

**Comment by dlumbrer** [comment]
I'm going to change the version of the plugin, thanks.
