### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...).register

### ISSUE THREAD

**Issue by pedrolarva** [dlumbrer/kbn_network#40]
Hi!

very good this project.. I try to use in kibana 5.6.2, becase i have this version in production. 

But when i try to install this plugin, a get this error: 

Uncaught TypeError: __webpack_require__(...).register is not a function (https://elk.softbox.com.br/bundles/kibana.bundle.js?v=15543:334)

Any sugestions? 

![screenshot from 2017-10-03 19-37-11](https://user-images.githubusercontent.com/1556612/31152403-480c23de-a872-11e7-98c7-1eacf54c65a5.png)

**Comment by dlumbrer** [comment]
Download the latest version, the 5.5.x branch and change the version of the package.json to "5.6.2"

**Comment by pedrolarva** [comment]
Showw!!!

Its realy show!!!

**Comment by ntim** [comment]
@dlumbrer changed the packaged version to 5.6.2 but the error still persists.

**Comment by robcowart** [comment]
Follow the instructions here...

https://www.linkedin.com/pulse/visualize-network-traffic-connections-elastiflow-kbn-robert-cowart/

Obviously set package.json to your version of Kibana, as long as you are using 5.5.x or 5.6.x

Make sure you delete KIBANA_HOME/optimize/bundles before you restart Kibana
