### ISSUE TITLE
Order nodes by score?

### ISSUE THREAD

**Issue by pkmital** [dlumbrer/kbn_network#41]
Hi,
Thanks for a great plugin!  I'm just trying to learn how to use it still and can't seem to find a way to order my nodes based on the elasticsearch score?  For instance if I search for "javascript" in my document collection, I can't seem to find a good way to avoid sorting the results by their titles alphabetically?

![screen shot 2017-10-06 at 5 14 35 pm](https://user-images.githubusercontent.com/429252/31302854-0931301a-aaba-11e7-8ddb-7c48bd6f229a.png)

**Comment by dlumbrer** [comment]
Hi @pkmital,

You can order the nodes in the tab "Order by" inside the "Node" bucket.
