### ISSUE TITLE
This plugin changes the native Kibana tooltip/position

### ISSUE THREAD

**Issue by maziyarpanahi** [dlumbrer/kbn_network#42]
Hi,

Unfortunately, my installation of this plugin in the latest version of Kibana (5.6.2 and 5.6.3) changed the style and position of tooltips for the entire visualisations/dashboard. 

I reported this issue initially in Kibana repo, but it turns out it is kbn_network:
https://github.com/elastic/kibana/issues/14589

Many thanks for your plugin i really enjoying it, I thought it might be helpful to report this.

Best,
Maziyar

**Comment by dlumbrer** [comment]
Hi @maziyarpanahi ,

You are right, the problem is that the names of the tooltips css are the same.
I will take a look and fix it!

Thx

**Comment by dlumbrer** [comment]
Solved!

**Comment by maziyarpanahi** [comment]
Thanks mate! I really appreciate your work 👍
