### ISSUE TITLE
Crashing with kibana version 5.6.3

### ISSUE THREAD

**Issue by TheReal1604** [dlumbrer/kbn_network#44]
with this error: Uncaught TypeError: __webpack_require__(...).register is not a function(http://localhost:5601/bundles/kibana.bundle.js?v=15554:335)

Maybe you got an idea?

**Comment by dlumbrer** [comment]
Did you downloaded the release for 5.6X versions?

Thx

**Comment by TheReal1604** [comment]
I cloned the master repo to my system.

**Comment by dlumbrer** [comment]
So, this is the problem.

Clone the branch 5.5.X instead of master, this should work.
