### ISSUE TITLE
Error installing plugin for Kibana 5.6.3

### ISSUE THREAD

**Issue by czam01** [dlumbrer/kbn_network#45]
Currently we are working with kibana-5.6.3 i downloaded the plugin form the branch for 5.X and the follow all the steps, the service starts ok but when we are goint to add visualization we could not see the network option. It does not appear in the visualization menu.

The folder is install in /usr/share/kibana/plugins

If we see the logs it appear
FATAL Error: Config schema already has key: network_vis
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:51:13)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:19:12
    at next (native)
    at step (/usr/share/kibana/src/server/plugins/plugin_collection.js:49:191)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:49:361

**Comment by dlumbrer** [comment]
You have to change the tag "version" in the package.json to "5.6.3".

**Comment by czam01** [comment]
Thank You, It works in this way: 

sudo git clone https://github.com/dlumbrer/kbn_network.git -b 5.5.x /usr/share/kibana/plugins/network_vis/ 

Then edit package.json  and let it: 

"name": "network_vis",
  "version": "5.6.3",

Restart
ubuntu@:/usr/share/kibana/plugins/network_vis$ sudo -i service kibana stop
ubuntu@:/usr/share/kibana/plugins/network_vis$ sudo -i service elasticsearch stop
ubuntu@:/usr/share/kibana/plugins/network_vis$ sudo -i service elasticsearch start
ubuntu@:/usr/share/kibana/plugins/network_vis$ sudo -i service kibana start
