### ISSUE TITLE
network_vis inside docker-kibana

### ISSUE THREAD

**Issue by ranayayas** [dlumbrer/kbn_network#46]
Hi,

I install as guided. My kibana is inside docker
cd KIBANA_HOME/plugins
git clone https://github.com/dlumbrer/kbn_network.git network_vis
cd network_vis
rm -rf images/
npm install

change the version to the Kibana (5.6.1). 

However I cannot see the 'network' visualisation menu in Kibana.
log   [09:09:33.979] [warning] Plugin "network_vis" was disabled because it expected Kibana version "5.6.1", and found "5.5.2".

I did it in Kibana in a other machine (without docker), no problem.
Is there any special treatment for docker?

Tks

**Comment by ranayayas** [comment]
When I tried to run Kibana manually inside docker:
log   [09:09:33.979] [warning] Plugin "network_vis" was disabled because it expected Kibana version "5.6.1", and found "5.5.2".

**Comment by dlumbrer** [comment]
Your Kibana's version is 5.5.2, so you have to change the version on package.json to 5.6.3 instead.

**Comment by ranayayas** [comment]
Tks. It's working now

**Comment by Foina** [comment]
Sorry may I ask where can I find a guide to install kibana and this plugin in docker
