### ISSUE TITLE
Incorrect labels for second-level nodes if "Edge Size" metric is selected

### ISSUE THREAD

**Issue by NeonSludge** [dlumbrer/kbn_network#49]
Hi.
I've noticed an issue with node labels after updating this plugin from the 6-dev branch. I'm currently running Kibana 6.1.0.

Steps to reproduce:
1. Create a "node-node" visualization. The network [is displayed](https://i.imgur.com/ecgNQ2C.png) without any issues.
2. Now select the "Edge Size" metric and refresh the visualization. Second-level nodes [now have numbers on their labels](https://i.imgur.com/Ju6Q7Ea.png) instead of the actual values. I assume those are doc counts from the terms aggregation.
3. Remove the "Edge Size" metric and select the "Node Size" one. Second-level nodes [now have correct labels](https://i.imgur.com/rf5S1hJ.png) and the first-level nodes are scaled accordingly.

I think that keys and values from the terms aggregation are getting mixed up somewhere when the "Edge Size" metric is selected.

**Comment by dlumbrer** [comment]
Hi @NeonSludge,

You are right, I'm going to fix this bug, sorry for the inconvenience.

**Comment by NeonSludge** [comment]
>

**Comment by dlumbrer** [comment]
Updated release

**Comment by NeonSludge** [comment]
Can confirm, this fixes the problem.
Thank you again.
