### ISSUE TITLE
which kibana 5 version 

### ISSUE THREAD

**Issue by alain2208** [dlumbrer/kbn_network#5]
Hi i'm not an npm expert i tried to do what you wrote and got this
on which version did the software expect to be instaled?

npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! Invalid version: "kibana"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\elastic\kibana-5.0.0-beta1-windows-x86\plugins\network_vis\npm-debug.log

**Comment by dlumbrer** [comment]
Hi alain2208

Rigth now I commited the code that fix this problem.

In the package.json of the plugin, in the "version" tag you need to put your Kibana version to fix the "npm install".

**Comment by alain2208** [comment]
thks 
i recloned your new version and no more the problem and don't need to play with the package.json
