### ISSUE TITLE
Kibana  6.3.0

### ISSUE THREAD

**Issue by gjelenc** [dlumbrer/kbn_network#56]
Not working with Kibana 6.3.0.
Error log: [kibana_6.3.0.log](https://github.com/dlumbrer/kbn_network/files/2101475/kibana_6.3.0.log)

**Comment by dlumbrer** [comment]
During this and next week I will update all my plugins to Kibana 6.3. 

Thx!!

**Comment by dlumbrer** [comment]
Done in faf6179 :+1:
