### ISSUE TITLE
When installing on kibana 6.1 the plugin breaks

### ISSUE THREAD

**Issue by shishircc** [dlumbrer/kbn_network#57]
I get following error on trying to install this plugin in kibana 6.1 

_schemas.Schemas is not a constructor at Object.""networkvistypeprovider""

What could be the issue ?

**Comment by dlumbrer** [comment]
I will add a version for Kibana 6.3 and other for Kibana 6.2 or lower.

During this weekend I will do it. If you want to install it now, please download the version of this commit: aeffc7c0015757765554126948e4d7724cf4b592

**Comment by dlumbrer** [comment]
Fixed, I prepared a new branch for Kibana 6.0, 6.1 and 6.2: `6.2-dev`

I updated the README.md adding new instructions.

The release for Kibana 6.0 6.1 and 6.2 is https://github.com/dlumbrer/kbn_network/releases/tag/6.0.X-2
