### ISSUE TITLE
Missing relations between nodes

### ISSUE THREAD

**Issue by NeonSludge** [dlumbrer/kbn_network#58]
There is an issue with displaying relations between nodes in the latest plugin version for Kibana 6.

Kibana version: 6.3.0.
Plugin version: installed from the `6-dev` branch (commit faf6179).

Steps to reproduce: 

1. Create a Node-Node or Node-Relation network.
2. Relations between nodes are missing even if the nodes are definitely related.

Here is an example where the network was supposed to show relations between some application servers based on what cluster they're in: https://i.imgur.com/MzgHRVH.png. The data behind the visualization is 100% correct and the visualization worked fine before the update.

**Comment by dlumbrer** [comment]
I have to review it this weekend, thanks

**Comment by dlumbrer** [comment]
Fixed!

**Comment by NeonSludge** [comment]
Can confirm, the latest release works fine.
Thank you!
