### ISSUE TITLE
Multiple Visualisations on One Dashboard

### ISSUE THREAD

**Issue by lawton27** [dlumbrer/kbn_network#6]
When multiple network visualisations are added to the same Kibana dashboard, only one functions.

Cheers,
Jack :)

**Comment by dlumbrer** [comment]
Hi Jack

Im ready developing this function, sorry for the late.

Thanks for writing

David

**Comment by cgiraldo** [comment]
Hi David,
I am hitting the same issue.
Any estimate time to complete?

BTW, nice work!
Carlos

**Comment by dlumbrer** [comment]
Hi @cgiraldo ,

Im very busy now, but this is the next improve that will be added.

I'm sorry for the delay, I will close this issue when the funcionality will be added.

Thanks for writing and the feedback!

David
