### ISSUE TITLE
Not working with Kibana 6.5.X

### ISSUE THREAD

**Issue by gjelenc** [dlumbrer/kbn_network#62]
I did the reinstall of plugin and doesn't help.
Also optimize is not showing kbn_network plugin

`{"type":"log","@timestamp":"2018-11-22T07:36:40Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, space_selector, login, logout, dashboardViewer, apm, canvas, infra and kibana. This may take a few minutes"}
{"type":"log","@timestamp":"2018-11-22T07:42:17Z","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, space_selector, login, logout, dashboardViewer, apm, canvas, infra and kibana complete in 336.98 seconds"}`

**Comment by dlumbrer** [comment]
I'm going to work on this! Thanks for the notice!

**Comment by gjelenc** [comment]
Maybe this help's you: https://www.elastic.co/blog/kibana-plugin-api-changes-in-6-5

**Comment by gjelenc** [comment]
Any progress on issue ?

**Comment by anthonyleonard** [comment]
Try the following at the command prompt while kibana is stopped, then start it up again:

export NODE_OPTIONS="--max-old-space-size=5000"

**Comment by gjelenc** [comment]
If I set this option, I will get this error:
/usr/share/kibana/bin/../node/bin/node: "--max-old-space-size=5000" is not supported in NODE_OPTIONS

**Comment by syunusic** [comment]
Same problem here.
+1

**Comment by Tarik-H** [comment]
Is it working with kibana 6.5.4? When I issue npm install I no longer can start Kibana !

**Comment by syunusic** [comment]
> Is it working with kibana 6.5.4? When I issue npm install I no longer can start Kibana !

as Jan 4th 2019, this plugin is not working in 6.5.2, so I guess (pretty sure) won't work on 6.5.4.
BUT... I don't think this makes Kibana not starting. When I Upgrade from 6.4.x to 6.5.x it took a very long time to start Kibana, due some optimization processes.
Botom line: this plugin won't work, but won't be the reason Kibana is not working.

**Comment by dlumbrer** [comment]
@syunusic is right.

Next week I'm going to update the plugin (and the others) to the Kibana 6.5.X versions.

**Comment by dlumbrer** [comment]
The plugin now supports 6.5.X version!!! (tested on 6.5.4)

In releases there are the binares and the source code:
- https://github.com/dlumbrer/kbn_network/releases/tag/6.5.X-1

Sorry for the long wait and thanks for the support!
