### ISSUE TITLE
How to visualize additional information between 2 nodes?

### ISSUE THREAD

**Issue by Tarik-H** [dlumbrer/kbn_network#64]
I apologize for this newbie question: Is it possible to visualize additional data on the Edges ? for example in a relationship between two nodes (ip addresses) is it possible to see the protocol port number as well?

**Comment by dlumbrer** [comment]
Hi @Tarik-H ,

There is an USER_GUIDE.md file with the steps in order to show different info with the plugin, please take a look and tell me if that is enough.

Thanks
