### ISSUE TITLE
No Map loading in visualizer

### ISSUE THREAD

**Issue by njdonarski** [dlumbrer/kbn_network#66]
The plugin sits at the same unloaded image

![loading_net](https://user-images.githubusercontent.com/30577973/51654825-49155600-1f5f-11e9-95af-d5daeeb371cf.JPG)

**Comment by dlumbrer** [comment]
Thats strange, what version of the plugin and kibana are you running?

**Comment by timoSwalter** [comment]
I'm having the same Issue. 
I'm running Kibana 6.4.2 and used a fresh installation from the network_vis-6.tar.gz file

**Comment by joost2** [comment]
Same here with Kibana 6.5.4 & the latest version of the plugin.

**Comment by joost2** [comment]
Let me know if you need any information/output from my installation.

**Comment by dlumbrer** [comment]
I have to prepare another release, could you try to use the version from the source code of the 6-dev branch?

**Comment by joost2** [comment]
I just tried it, but it remains stuck with "Loading network..." in the top right corner of the screen.

**Comment by dlumbrer** [comment]
I tried the version from 6-dev and it works... could you send me a picture with the aggregations menu (maybe it does not admits some fields)

**Comment by joost2** [comment]
Sorry for not getting back on this earlier - I got this to work again whilst troubleshooting another Kibana plugin, which was spitting out errors related to read-only file permissions. After doing a "chown -R kibana.kibana /usr/share/kibana/" the problematic plugin started to work... and so did the kbn_network plugin!
