### ISSUE TITLE
Load the visualisation with own JSON data

### ISSUE THREAD

**Issue by marcleibold** [dlumbrer/kbn_network#68]
Hi,

I am currently trying to feed my own data which is the output of a python script i wrote into your plugin.
I already tried to do it via curl and just overwrite the visualisation in the .kibana index but I just can't get the formatting right, so that the vis shows a graph according to my JSON input.
The JSON input only contains 2 lists (edges and nodes), just like the format some of your examples from the HTML files in the plugin directory use.

How do I implement this data in a curl statement? Or is that even possible?

**Comment by dlumbrer** [comment]
Hi,

Visualizations of Kibana uses ES aggregation, so you need to understand how it works in order to make graphs.

It is impossible to use the plugin just with normal JSON. I recommend you to use the library vis.js instead

Thanks
