### ISSUE TITLE
Compatibility with Kibana 7.x

### ISSUE THREAD

**Issue by fpompermaier** [dlumbrer/kbn_network#71]
Any plan to support Kibana 7.x?

**Comment by dlumbrer** [comment]
Yes, but I don't know when it will be done!

**Comment by craig-cogdill** [comment]
I have only done testing of basic node/relation functionality, but the latest `6-dev` branch appears to work just fine. This is using ES and Kibana 7.1.1 for Mac with default configuration.

**Comment by gyterpena** [comment]
Looks like upgrade to 7.2.0 broke it. Visualization is stuck on "Loading" message. I could not find any helpful logs in kibana.log or cluster logs.
![image](https://user-images.githubusercontent.com/39734663/60416062-30c7f800-9bdd-11e9-9630-b481816a715b.png)

**Comment by YoullNeverSee** [comment]
> 
> 
> Looks like upgrade to 7.2.0 broke it. Visualization is stuck on "Loading" message. I could not find any helpful logs in kibana.log or cluster logs.
> ![image](https://user-images.githubusercontent.com/39734663/60416062-30c7f800-9bdd-11e9-9630-b481816a715b.png)
> Edit. I tried rolling back to 7.1.1, works with 6-dev version
> 
> Console on chrome for kibana 7.2 shows this error
> 
> vendors.bundle.dll.js:516 TypeError: Cannot read property 'schema' of undefined
> at commons.bundle.js:3
> at Array.forEach ()
> at commons.bundle.js:3
> at commons.bundle.js:3
> at Scope.$digest (vendors.bundle.dll.js:516)
> at Scope.$apply (vendors.bundle.dll.js:516)
> at commons.bundle.js:3
> at new Promise ()
> at AngularVisController.render (commons.bundle.js:3)
> at _callee$ (commons.bundle.js:3)

Got the same at 7.3.0
But no hint where to look for the breaking changes!
Agreed 7.1.1 works so far!
But best @6.7.2 as last Build

Please Add Support for 7th Series

Thanks and Brdgs

**Comment by dlumbrer** [comment]
The plugin has not a version for Kibana 7 for now. It is my highest priority task.

Thanks for the understanding

**Comment by Tarik-H** [comment]
Will there be any update to support 7.x?
Thanks

**Comment by syunusic** [comment]
Please!!!! Support for 7.4.x!!!!

**Comment by dkngyn** [comment]
`visData` has changed  since 7.2, `columns` no longer includes `AggConfig`
Happy to take this issue and open a PR.

**Comment by dlumbrer** [comment]
> `visData` has changed since 7.2, `columns` no longer includes `AggConfig`
> Happy to take this issue and open a PR.

Go for it! :smile:

**Comment by dlumbrer** [comment]
Nice work @dkngyn , I commented on the PR, thanks

**Comment by syunusic** [comment]
Should it work with:
```
git clone https://github.com/dlumbrer/kbn_network.git network_vis -b 7-dev
```
?
That last change was only for 7.2? Should it work on 7.4?

**Comment by danJsonar** [comment]
@syunusic these are complied codes it should work right away. I've not tested on 7.4 but I know it doesn't on work on 7.5 because the schemas change again, with somewhat confidence I think the 7.4 still has the same schemas as 7.2.

**Comment by dkngyn** [comment]
@syunusic these are complied codes it should work right away. I've not tested on 7.4 but I know it doesn't on work on 7.5 because the schemas change again, with somewhat confidence I think the 7.4 still has the same schemas as 7.2.

**Comment by syunusic** [comment]
@dkngyn What I did is: 
```
# rm -rf network_vis/
# git clone https://github.com/dlumbrer/kbn_network.git network_vis -b 7-dev
# rm -rf images/
# npm install
```
I did the same with the "main" (without the "-b" option). Same result.. not working. It stays in "loading". Do I have to do anything else?

**Comment by dkngyn** [comment]
@syunusic it looks right, you can confirm the branch you've checked out by `$ git branch` on when you're in `network_vis` dir. You can also look for [this part of code](https://github.com/dlumbrer/kbn_network/blob/7-dev/public/network_vis_controller.js#L69-L97) exists.

If it still doesn't work. Could you post your browser console error message?

**Comment by syunusic** [comment]
@dkngyn : 
```
$ git branch
* 7-dev
```

I look at the code you say and it is exactly the same.
Here is the console error:
```
TypeError: Cannot read property 'schema' of undefined
    at commons.bundle.js:5
    at Array.forEach (<anonymous>)
    at commons.bundle.js:5
    at commons.bundle.js:3
    at Scope.$digest (vendors.bundle.dll.js:417)
    at Scope.$apply (vendors.bundle.dll.js:417)
    at commons.bundle.js:3
    at new Promise (<anonymous>)
    at AngularVisController.render (commons.bundle.js:3)
    at _callee$ (commons.bundle.js:3)
```

**Comment by syunusic** [comment]
Should I do anything to fix the problem in 7.4?

**Comment by dkngyn** [comment]
@syunusic it seems like you have the browser cache still, because the `7-dev` code doesn't have any `.schema` property. If cleaning your browser cache doesn't solve this issue then please pm me.

**Comment by syunusic** [comment]
@dkngyn you was right. I'm using Kibana with Docker (docker-compose) and I had to destroy the project and re create it. After that, works perfectly. Gracias!

**Comment by fpompermaier** [comment]
In my Kibana 7.5 the 7-dev branch gives the following error:

` Error: Optimizations failure.\n   8329 modules\n    \n    ERROR in ./plugins/network_vis/public/network_vis.js\n    Module not found: Error: Can't resolve 'ui/registry/vis_types' in '/usr/share/kibana/plugins/network_vis/public'\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:440:26)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n   `

**Comment by mejarrett** [comment]
The 7-dev branch still had two bugs that prevented @craig-cogdill and I from using it out of the box. I've put up this PR, tested with Kibana 7.2: https://github.com/dlumbrer/kbn_network/pull/78

**Comment by coryk2049** [comment]
> @dkngyn you was right. I'm using Kibana with Docker (docker-compose) and I had to destroy the project and re create it. After that, works perfectly. Gracias!

Confirmed to be working with 7.4.2. Hope some kind person will make it work for 7.5.x soon.

**Comment by mejarrett** [comment]
@fpompermaier This plugin isn't compatible with Kibana 7.5 yet. From this [PR](https://github.com/elastic/kibana/pull/46323) it looks like that the import of vis_types needs to be updated for 7.5, and the comments in this thread regarding schema changes likely need to be addressed.

**Comment by dkngyn** [comment]
@fpompermaier I did confirm this change doesn't work on v7.5 as in my previous comment.

**Comment by mejarrett** [comment]
I put up this [PR](https://github.com/dlumbrer/kbn_network/pull/79) for 7.5.x compatibility. I've done testing with Kibana 7.5.0, 7.5.1, and 7.5.2 on Mac.

**Comment by dlumbrer** [comment]
Sorry for the delay, these months have been complicated. I just updated the releases and the branches, thanks :)
