### ISSUE TITLE
How to reduce the distance of any unrelated clusters

### ISSUE THREAD

**Issue by yhgcn** [dlumbrer/kbn_network#8]
The distance of any clusters is too long, how to use options to shorten the distance of any clusters.

![3](https://cloud.githubusercontent.com/assets/18245164/21419590/89dc80aa-c863-11e6-99e2-49a149dc3469.png)

**Comment by dlumbrer** [comment]
Now, its not possible to short this distance, sorry.

I want to add more options to change the physics as you like, you will notified when this functionality will be developed.

Thanks,

David

**Comment by yhgcn** [comment]
Could you make gravitationalConstant and springConstant of network_vis_controller.js to adjustable variables in the "view options"?Choose a different size of gravitationalConstant and springConstant, style is also different.
![aaa](https://cloud.githubusercontent.com/assets/18245164/21564728/9481808c-cecb-11e6-8917-92089be5bf30.png)

**Comment by dlumbrer** [comment]
Yeah, that's what I thought. Now im busy, but that is the next functionality that i will add.

Thanks.
