### ISSUE TITLE
why no detail guide for "relation "

### ISSUE THREAD

**Issue by afanger** [dlumbrer/kbn_network#9]
There's no detail information for 'Relation' in the user guide.
the graph for Node & Relation is quite different from that for the two type of nodes.
what 's the meaning ?I can't  see the text araround the nodes clearly in the figures.
Would you plz put an example dataset file ,maybe it helps to make sense.

By the way , is there any way using this plugin to show the  co-occurrence network of  papers or  publications or projects?
Thanks.

**Comment by dlumbrer** [comment]
"Relation" is used for make the relation of the nodes. Is detailed the use in the User Guide, with examples to build differents networks. In other words, you can build 2 types of networks: "Node & Node" with 2 types of nodes and "Node & Relation" with 1 type of nodes but the relation is defined by "Relation" aggregation.

You can build networks like: "one type of node are the projects and the other type are the authors" or "nodes are the authors and have relation if they contributed in the same project", etc.

Sorry for the misunderstood, i will think how to change the user guide.

Thanks for writing and sorry for the delay,

**Comment by afanger** [comment]
I get it，thank you ！
