### ISSUE TITLE
Support for Kibana 7.10.x

### ISSUE THREAD

**Issue by coryk2049** [dlumbrer/kbn_network#93]
Hello,

Followed the instructions from here:

https://github.com/dlumbrer/kbn_network

and no joy, details of the errors below:

`[<KIBANA_HOME>/bin]# ./kibana-plugin --allow-root install file:///home/ec2-user/kibana_plugins/kbn_network.tgz
Found previous install attempt. Deleting...
Attempting to transfer from file:///home/ec2-user/kibana_plugins/kbn_network.tgz
Transferring 27818147 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /usr/share/kibana/node_modules/yauzl/index.js:187:14
    at /usr/share/kibana/node_modules/yauzl/index.js:631:5
    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"`

Any pointers appreciated to support Kibana 7.10.x 

Cheers!

**Comment by dlumbrer** [comment]
The support for Kibana 7.10.0 is now available at "releases" section
